name: LMU_DA_ML
dependencies:
    - python==3.10
    - pip
    - graphviz
    - pip:
      - numpy
      - pandas>=1.5.3
      - scikit-learn
      - matplotlib
      - seaborn
      - jupyterlab
      - tensorflow~=2.11
      - pyaml
      - pydot
      - graphviz
      - tables
      - ipywidgets
